<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard2.0;net7.0-windows;net8.0-windows</TargetFrameworks>
    <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>

    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles Condition="'$(Configuration)' == 'Debug'">True</EmitCompilerGeneratedFiles>

    <AnalysisMode>recommended</AnalysisMode>
    <AnalysisModePerformance>all</AnalysisModePerformance>
    <AnalysisModeInteroperability>none</AnalysisModeInteroperability>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>wincred</RootNamespace>

    <LangVersion>latest</LangVersion>
    <RollForward>LatestMajor</RollForward>
    <DebugType>portable</DebugType>
    <DebugSymbols>True</DebugSymbols>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>True</IncludeSymbols>
    <Version>0.1.0</Version>

    <PackageId>$(AssemblyName)</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <PackageDescription>Low-alloc interaction with the Windows Credential Manager.</PackageDescription>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jolaquai/$(AssemblyName)</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
      <None Include="..\LICENSE;..\README.md" Pack="True" PackagePath="/" />

      <Using Include="System.Diagnostics" />

      <Using Include="System.Runtime.CompilerServices" />
      <Using Include="System.Runtime.InteropServices" />

      <Using Include="System.Text" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
      <Compile Remove="**/*.net7.0.cs" />
      <None Include="**/*.net7.0.cs" />
      <PackageReference Include="System.Memory" Version="4.6.3" />
      <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0-windows' OR '$(TargetFramework)' == 'net8.0-windows'">
      <Compile Remove="**/*.netstandard2.0.cs" />
      <None Include="**/*.netstandard2.0.cs" />
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
      <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

</Project>
