# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 11.0.x
    - name: Restore dependencies
      run: dotnet restore wincred/wincred.csproj
    - name: Build
      run: dotnet build wincred/wincred.csproj --no-restore -c Release
    - name: Test
      run: dotnet test wincred/wincred.csproj --no-build -c Release --verbosity normal
    - name: Publish
      run: dotnet publish wincred/wincred.csproj --no-build -c Release -o artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wincred
        path: artifacts/wincred.dll
